import Head from 'next/head'
import Image from 'next/image'
import About from './About';
import Projects from './Projects';
import styles from '../styles/Home.module.css'
// import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react';
import Link  from 'next/link';
import Main from './Main';
// import Head from 'next/head';

export default function Home() {
  return (
    <div >
      <Head>
      <title>James Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://aniyuki.com/wp-content/uploads/2021/12/aniyuki-sad-anime-avatar-image-91.jpg" />
        
      </Head>
      <Main />
      <About className="w-screen"/>
      <Projects  />
          <div className=''>  
            
          </div>

  </div>)
}
